(function(g){var window=this;var N7=function(a,b){return g.aa[a]=b},ita=function(a,b){var c=new g.ek;
c.o=a.o;c.D=a.D;c.C=a.C;c.B=a.B;c.isDefault=!1;c.G=a.G;c.F=a.F;c.H=a.H;c.g=b;return c},O7=function(a){return a.g?a.g.languageCode:a.o},P7=function(a){var b={format:a.A,
languageCode:a.o,languageName:a.D,displayName:g.fk(a),kind:a.B,name:a.C,id:a.wa,is_servable:a.O,is_default:a.isDefault,is_translateable:a.G,vss_id:a.F};a.g&&(a=a.g,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.g,id:a.id,is_default:a.isDefault});return b},Q7=function(){this.timestamp=this.Te=0;
this.g=!1},R7=function(){this.g=0},S7=function(a){this.A=[];
for(var b=0;15>=b;b++){this.A[b]=[];for(var c=0;32>=c;c++)this.A[b][c]=new Q7}this.g=this.o=this.Bc=0;this.style=new R7;this.C=a;this.B=0},T7=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.C.o+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var t=a.A[m][q];
if(0!=t.Te){0==c&&(c=m,d=q);var n=String.fromCharCode(t.Te),v=t.timestamp;v<e&&(e=v);t.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==t.Te||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.C.o+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.A[k][m],t=q.Te,0!=t&&(0==c&&(c=k,d=m),n=String.fromCharCode(t),v=q.timestamp,v<=e&&(e=v),l+=n,q.reset()),32==m||0==t)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},U7=function(a){return a.A[a.Bc][a.o]},V7=function(a,b,c){2<=b&&1<
a.o&&(--a.o,U7(a).Te=0);
var d=U7(a);d.timestamp=a.C.o+0;a:{switch(b){case 0:b=jta[(c&127)-32];break a;case 1:b=kta[c&15];break a}b=0}d.Te=b;32>a.o&&a.o++},lta=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.A[b+e][f].Hl(a.A[c+e][f])},W7=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.A[b+d][e].reset()},X7=function(a){a.Bc=0<a.g?a.g:1;
a.o=1;W7(a,0,15)},Y7=function(a,b,c,d,e){g.ds.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},Z7=function(a,b,c,d,e,f,k){g.ds.call(this,a,a+b,{priority:c,
namespace:"captions"});this.windowId=d;this.text=e;this.C=f||!1;this.o=k||null},$7=function(a){this.B=a;
this.C=0;this.style=new R7;this.D=new S7(a);this.F=new S7(a);this.G=new S7(a);this.o=this.D;this.A=this.F;this.g=this.o},a8=function(a,b,c){var d=a.o;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:T7(d,c),X7(a.o),X7(a.A),d.Bc=15,d.g=b}a.style.set(3);a.g=d;a.g.style=a.style;a.B.mode=1<<d.B;d.o=1;d.g!=b&&(d.g>b?(T7(d,c),W7(d,d.Bc-d.g,b)):d.Bc<b&&(b=d.g),d.g=b)},mta=function(a){a.style.set(1);
a.g=a.A;a.g.g=0;a.g.style=a.style;a.B.mode=1<<a.g.B},nta=function(a){a.style.set(4);
a.g=a.G;a.g.style=a.style;a.B.mode=1<<a.g.B},b8=function(){this.o=this.A=this.g=0},pta=function(a,b,c){if(255==a&&255==b||!a&&!b)return{pl:a,
ql:b,result:0};a=ota[a];b=ota[b];if(a&128){if(!(b&128)&&0!=c.g&&c.o==b)return{pl:a,ql:b,result:1}}else if(b&128&&1<=a&&31>=a)return{pl:a,ql:b,result:2};return{pl:a,ql:b,result:3}},qta=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.rq=!0;break;case "u":k.yr=!0;break;case "font":var m=f.getAttribute("color");c8.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new Z7(a,b,c,d,n.nodeValue,e||0<m,g.Cb(k)?void 0:k));else{var q={};g.Aa(q,k);qta(a,b,c,d,e||0<m,n,q,l)}}},e8=function(a){var b="_"+d8++;
return new Y7(0,0x8000000000000,0,b,a||{})},f8=function(a){this.o=a;
this.g=new b8;this.C=0;this.A=new $7(a);this.D=new $7(a);this.B=this.A},rta=function(a,b,c,d){a.g.update();
b=pta(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.pl;c=b.ql;if(32<=e||!e)a.o.mode&a.o.A&&(b=e,b&128&&(b=127),c&128&&(c=127),e=a.B.g,b&96&&V7(e,0,b),c&96&&V7(e,0,c),!a.o.F&&0!=b&&0!=c&&3==e.style.g&&T7(e,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.A=e,b.o=c,b.g=2,b=e&8?a.D:a.A,a.B=b,a.o.mode=1<<(a.C<<2)+(b.C<<1)+(4==b.style.g?1:0),(a.o.mode|1<<(a.C<<2)+(b.C<<1)+(4!=b.style.g?1:0))&a.o.A))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&
14)>>1):0;c=b.g;switch(b.style.get()){case 4:d=c.Bc;break;case 3:if(d!=c.Bc){if(d<c.g&&(d=c.g,d==c.Bc))break;var f=1+c.Bc-c.g,k=1+d-c.g;lta(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));W7(c,b,e)}}c.Bc=d;c.o=a+1}else switch(e&7){case 1:switch(c&112){case 32:V7(b.g,0,32);break a;case 48:57==c?(b=b.g,U7(b).Te=0,32>b.o&&b.o++):V7(b.g,1,c&15)}break;case 2:c&32&&V7(b.g,2,c&31);break;case 3:c&32&&V7(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:mta(b);break;
case 33:b=b.g;1<b.o&&(--b.o,U7(b).Te=0);break;case 36:b=b.g;d=U7(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.A[a][c]==d){for(;32>=c;c++)b.A[a][c].reset();break}break;case 37:a8(b,2,d);break;case 38:a8(b,3,d);break;case 39:a8(b,4,d);break;case 40:V7(b.g,0,32);break;case 41:b.style.set(2);b.g=b.o;b.g.g=0;b.g.style=b.style;b.B.mode=1<<b.g.B;break;case 42:d=b.G;d.g=15;d.style.set(4);X7(d);nta(b);break;case 43:nta(b);break;case 44:a=b.o;switch(b.style.get()){case 1:case 2:case 3:T7(a,d)}W7(a,0,15);break;
case 45:b:{a=b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.Bc){++a.Bc;a.o=1;break b}case 3:}2>a.g&&(a.g=2,a.Bc<a.g&&(a.Bc=a.g));b=a.Bc-a.g+1;T7(a,d);lta(a,b,b+1,a.g-1);W7(a,a.Bc,1)}break;case 46:W7(b.A,0,15);break;case 47:T7(b.o,d);d=b.A;a=b.B.o+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.A[c][e].timestamp=a;d=b.A;b.A=b.o;b.o=d;mta(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.g,32<(b.o+=c&3)&&(b.o=32)}}},sta=function(){},uta=function(a){var b=tta(a);
b.toString(16);if(1380139777!=b)return!1;a.version=g8(a);if(1<a.version)return!1;g8(a);g8(a);g8(a);return!0},h8=function(a,b,c){this.F=c;
this.version=this.C=this.D=this.g=0;this.A=new window.DataView(a);this.o=[]},g8=function(a){var b=a.g;
a.g+=1;return a.A.getUint8(b)},tta=function(a){var b=a.g;
a.g+=4;return a.A.getUint32(b)},vta=function(a,b,c){var d=a.getAttribute("t"),d=d?(0,window.parseInt)(d,10):1E3*(0,window.parseFloat)(a.getAttribute("start")||0),e=a.getAttribute("d"),e=e?(0,window.parseFloat)(e):1E3*(0,window.parseFloat)(a.getAttribute("dur")||0);
b=a.getAttribute("w")||b;var f=!!a.getAttribute("append"),k=f?6:5;a=g.zt("<html>"+(a.firstChild&&a.firstChild.nodeValue||"")+"</html>");qta(d,e,k,b,f,a.firstChild,{},c)},i8=function(a){this.F=a;
this.B=this.o=this.mode=this.A=0;this.C=new f8(this);this.D=new f8(this);this.g=[];this.clear()},wta=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.B&&a.reset(),a.C.g.clear(),a.D.g.clear()):(a.B=0,rta(a.C,b,c,d))},xta=function(a,b){a.g.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.o=d.time;0==d.type?wta(a,d.$t,d.au,b):1==d.type&&a.A&496&&rta(a.D,d.$t,d.au,b)}a.g.length=0},j8=function(){},yta=function(a,b){for(var c in a)if(!(c in b)||a[c]!==b[c])return!1;
for(c in b)if(!(c in a))return!1;return!0},k8=function(){this.A={};
this.o=null},l8=function(){this.o=null},zta=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.rq=!0;break;case "u":l.yr=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType)q=new Z7(b,c,d,e.id,q.nodeValue,f||0<n,g.Cb(l)?void 0:l),m.push(q),e!=a.o&&e.o.push(q);else{var t={};g.Aa(t,l);zta(a,b,c,d,e,!0,q,t,m)}}},m8=function(a){a=a.split(":");
for(var b=0,c=0;c<a.length;c++)b=60*b+(0,window.parseFloat)(a[c]);return 1E3*b},n8=function(a){this.A=a;
this.o=new i8(!0);this.o.A=1},o8=function(a){this.o={};
this.C={};this.D={};this.A="_"+d8++;this.B=a},p8=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},q8=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},r8=function(a,b){var c=p8(a,b);
if(void 0!=c)return c},s8=function(a,b){var c=a.getAttribute(b);
if(null!=c)return c8.test(c),c},Ata=function(a,b){var c={},d=b.getAttribute("ws");
g.Aa(c,d?a.D[d]:a.B);d=r8(b,"mh");null!=d&&(c.zq=d);d=r8(b,"ju");null!=d&&(c.textAlign=d);d=r8(b,"pd");null!=d&&(c.dj=d);d=s8(b,"wfc");null!=d&&(c.windowColor=d);d=p8(b,"wfo");void 0!=d&&(c.ij=d/255);return c},Bta=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Aa(c,a.C[d]);d=r8(b,"ap");null!=d&&(c.vg=d);d=p8(b,"cc");null!=d&&(c.ou=d);d=p8(b,"ah");null!=d&&(c.Ch=d);d=p8(b,"rc");null!=d&&(c.fn=d);d=p8(b,"av");null!=d&&(c.Jh=d);return c},Cta=function(a,b,c){var d={};
g.Aa(d,Bta(a,b));g.Aa(d,Ata(a,b));c?(c=a.A,yta(d,a.B)&&(d=a.B)):c=b.getAttribute("id")||"0";a=p8(b,"t");b=p8(b,"d")||0x8000000000000;return new Y7(a,b,0,c,d)},t8=function(a){this.A=a;
this.o=null},Dta=function(){this.A=[];
this.g=[];this.o=-1},u8=function(a,b){return b?a.g.concat(a.A):a.g},v8=function(a,b){switch(b.B){case "asr":Eta(b,a.A);
break;default:if(b.isDefault||0>a.o)a.o=a.g.length;Eta(b,a.g)}},Eta=function(a,b){g.ze(b,(0,g.z)(a.J,a))||b.push(a)},Fta=function(a,b){var c=g.ye(a.g,(0,g.z)(b.J,b));
-1!=c&&(a.o=c)},w8=function(a){if(!Gta.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(Hta,"#$1$1$2$2$3$3"));a=a.toLowerCase();return[(0,window.parseInt)(a.substr(1,2),16),(0,window.parseInt)(a.substr(3,2),16),(0,window.parseInt)(a.substr(5,2),16)]},x8=function(){this.xa=[]},y8=function(a,b,c,d,e){g.H.call(this);
this.J=b;this.F=new x8;this.g=null;this.C=d;this.A=this.o=null;this.O=c;this.B=e||!1;this.G=new g.tz(this.H,1E3,this);g.J(this,this.G);b.addEventListener("seekto",this.D,this);this.D(b.getCurrentTime());this.H()},z8=function(a,b,c,d,e,f){this.C=[];
this.H=!1;this.A=a;this.F=[];this.G=[];this.Ea=e;this.Ca=f;this.D=null;this.P=.96*e;this.ka=.96*f;this.o={};g.Aa(this.o,b);g.Aa(this.o,this.A.params);g.Aa(this.o,c);e={};g.Aa(e,b.fb);this.A.params.fb&&g.Aa(e,this.A.params.fb);g.Aa(e,c.fb);this.o.fb=e;this.oa=c;g.V.call(this,{K:"div",Z:"caption-window",$:{id:"caption-window-"+a.id,dir:1==this.o.dj?"rtl":"ltr",tabindex:0,"aria-live":"assertive",lang:this.o.lang},S:[{K:"span",Z:"captions-text"}]});this.B=this.pa["captions-text"];this.fa=null!=this.B.style["box-decoration-break"]||
null!=this.B.style["-webkit-box-decoration-break"];this.J=d/360*16;this.type=0;this.aa=this.J*Ita(e);a=new g.qB(this.element,!0);g.J(this,a);a.subscribe("dragstart",this.FQ,this);a.subscribe("dragmove",this.EQ,this);a.subscribe("dragend",this.DQ,this);this.ca=this.ba=0;a="";this.o.ij&&(a=w8(this.o.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.o.ij+")");b={"background-color":a,display:!1===this.o.isVisible?"none":"","text-align":Jta[this.o.textAlign]};this.fa&&(b["border-radius"]=a?this.aa/
8+"px":"");g.Tt(this.element,b);switch(this.o.vg){case 0:case 1:case 2:g.N(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.N(this.element,"ytp-caption-window-bottom")}},Ita=function(a){var b=1+.25*(a.hi||0);
if(0==a.offset||2==a.offset)b*=.8;return b},A8=function(a,b){var c={};
if(null!=b.Ce||b.background){var d=null!=b.Ce?b.Ce:a.o.fb.Ce,e=w8(b.background?b.background:a.o.fb.background);c.background="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")";a.fa&&(c["box-decoration-break"]="clone",c["border-radius"]=a.aa/8+"px")}if(null!=b.hi||null!=b.offset)c["font-size"]=a.J*Ita(b)+"px";e=1;if(b.color||null!=b.Xg)d=w8(b.color||a.o.fb.color),e=null==b.Xg?a.o.fb.Xg:b.Xg,d="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")",c.color=d,c.fill=d;if(null!=b.Tf&&0!=b.Tf){var d="rgba(34, 34, 34, "+e+")",f=
"rgba(204, 204, 204, "+e+")";b.eu&&(f=d=b.eu);var k=a.J/16/2,l=Math.max(k,1),m=Math.max(2*k,1),e=Math.max(3*k,1),n=Math.max(5*k,1),q=[];switch(b.Tf){case 4:for(l=e;l<=n;l+=k)q.push(m+"px "+m+"px "+l+"px "+d);break;case 1:for(k=2<=window.devicePixelRatio?.5:1;l<=e;l+=k)q.push(l+"px "+l+"px "+d);break;case 2:q.push(l+"px "+l+"px "+f);q.push(-l+"px "+-l+"px "+d);break;case 3:for(l=0;5>l;l++)q.push("0 0 "+m+"px "+d)}c["text-shadow"]=q.join(", ")}d="";switch(b.fontFamily){case 1:d='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';
break;case 2:d='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:d='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:d='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:d='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:d=g.Op()?'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:d=
'Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}d&&(c["font-family"]=d);d=b.offset;null==d&&(d=a.o.fb.offset);switch(d){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.rq&&(c["font-style"]="italic");b.yr&&(c["text-decoration"]="underline");b.Lp&&(c.visibility="hidden");return c},Kta=function(a,b,c){a.H=a.H||!!c;
var d={};g.Aa(d,a.o.fb);g.Aa(d,c||b.o);g.Aa(d,a.oa.fb);var e=a.F[0],f;if(e&&d.background==e.background&&d.Ce==e.Ce&&!!d.Lp==!!e.Lp&&d.Tf==e.Tf){for(c=0;c<a.F.length;c++)if(yta(d,a.F[c])){f=a.G[c];break}if(!f){c={};for(var k in d)d[k]!=e[k]&&(c[k]=d[k]);f=g.qd("SPAN");g.Tt(f,A8(a,c));a.G[0].appendChild(f);c=1}a.G.length=c;a.F.length=c}else a.G.length=0,a.F.length=0,f=g.qd("SPAN"),g.Tt(f,A8(a,d)),a.B.appendChild(f);a.D&&a.D.parentNode!=f&&(g.Uq(a.D),f.appendChild(a.D));e=(k=g.y(b.text))?b.text.split("\n"):
[b.text];for(c=0;c<e.length;c++){var l=e[c];if(0<c||0==a.C.length||!b.C){if(0<c||0!=a.C.length){var m=g.qd("BR");f.appendChild(m)}f.appendChild(g.Oq("\u00a0"));a.D=g.Oq("\u00a0");f.appendChild(a.D)}l&&(m=a.D,m.parentNode&&m.parentNode.insertBefore(k?g.Oq(l):l,m))}a.F.push(d);a.G.push(f);a.C.push(b)},B8=function(a){this.ew=!!a;
this.g=new Dta;this.D=[];this.o=null},Mta=function(a){var b={};
if(a=O7(a))b.lang=a,Lta.test(a)&&(b.dj=1);return b},Nta=function(a,b,c,d,e){d=d||0;
e=e||0;if(g.y(b)){if("WEBVTT"==b.substring(0,6))return a.o||(a.o=new l8),a.o.g(b,d);b=g.zt(b);if(!b||!b.firstChild)return[];a.o||("timedtext"==b.firstChild.tagName?3==(0,window.parseInt)(b.firstChild.getAttribute("format"),10)?a.o=new o8(Mta(c)):a.o=new k8:a.o=new t8(Mta(c)));return a.o.g(b,d)}try{var f;if(g.y(b))f=!1;else{var k=new h8(b,0,0);f=uta(k)}if(f)return a.o||(a.o=new n8(e)),a.o.g(b,d)}catch(l){g.Sf(l)}return[]},Ota=function(a,b){return g.ze(u8(a.g,!0),function(a){return a.toString()==b})},
C8=function(a,b){B8.call(this);
this.B=a;this.Y=b;this.A=null},D8=function(a,b,c,d,e,f){z8.call(this,a,b,c,d,e,f);
g.N(this.element,"ytp-caption-window-rollup");this.type=2;this.L=this.W=0;this.M=window.NaN;this.ha=null;this.da=new g.tz(this.ua,433,this);g.J(this,this.da)},E8=function(a){if(!a.L){var b=g.qd("SPAN");
g.Tt(b,A8(a,a.o.fb));a.B.appendChild(b);b.appendChild(g.Oq("M"));var c=b.offsetHeight,d=g.qd("BR");b.appendChild(d);b.appendChild(g.Oq("M"));a.L=b.offsetHeight-c;a.B.removeChild(b)}return a.L},F8=function(a,b,c,d,e,f){z8.call(this,a,b,c,d,e,f);
this.type=1},G8=function(a,b,c,d){B8.call(this,d);
c=c||g.Hk(a).hl||"";c=c.split("_").join("-");this.B=g.Jk(a,{hl:c});this.C=b;this.F={};this.A=null},H8=function(a){B8.call(this,a.vl);
this.A=null;this.C=void 0;this.B=null;this.D=a.captionTranslationLanguages},Pta=function(a){for(var b in a)delete a[b]},L8=function(a){g.gv.call(this,a);
g.pi();this.X=g.X(a);this.B=a.getVideoData();this.da=g.PS(a);this.Y=a;var b=null,c=g.Rt("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.mB(c));this.W=b;this.C={fb:{}};this.D={fb:{}};this.J=[];this.H={};this.M={};this.O=!1;this.ha="1"==this.B.Pb.cc_auto_caps||"1"==this.X.L.cc_auto_caps;c=b=this.A=this.o=this.G=this.F=this.L=this.ca=null;I8(this)||(b=new g.tz(this.wz,0,this),g.J(this,b),c=new g.tz(this.tN,2E3,this),g.J(this,c));this.aa=b;this.fa=c;this.P=new g.oE(this);g.J(this,this.P);
I8(this)||this.P.V(a,"resize",this.Ar);this.P.V(a,"onPlaybackAudioChange",this.hJ);this.P.V(a,"crn_captions",this.nQ,this);this.P.V(a,"crx_captions",this.oQ,this);J8(this,K8(this,"display-settings")||{});Qta(this)&&this.load()},I8=function(a){return"3"!=a.X.B?!1:!!a.Y.app.F.pn()},Rta=function(a){var b;
a.B.captionTracks.length&&(b=a.g.Nh().Xt);if("FORCED_ON"==b||1==a.X.wg||1==a.B.wg||"alwayson"==a.B.hf("yt:cc"))return!0;if(2==a.X.wg){var c=K8(a,"module-enabled");if(null!=c)return!!c}return"ON"==b||"on"==a.B.hf("yt:cc")},Qta=function(a){return I8(a)?!a.B.za:a.B.captionTracks.length&&a.g.Nh().Dj?!0:Rta(a)},Tta=function(a,b){if(!g.X(a.g).experiments.g("legacy_default_captions")){if(a.o){var c=u8(a.o.g,b||a.ha),d=K8(a,"recent-langs");
if(d){for(var e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(d[e]==O7(c[f]))return c[f];for(e=0;e<d.length;e++)for(var k=d[e].match(Sta)[0],f=0;f<c.length;f++){var l=O7(c[f]).match(Sta)[0];if(k==l)return c[f]}}return a.G&&a.G.ci?a.G.ci:c[0]||M8(a)}return null}c=null;a.o&&(c=a.o.Xu(),!c&&b&&(c=u8(a.o.g,!0)[0]),c||!b&&!a.ha||(d=a.o.g.A,d.length&&(c=Ota(a.o,d[0].toString()))),c||(c=M8(a)));return c},M8=function(a){return g.X(a.g).experiments.g("legacy_default_captions")?a.o.Zu():a.G&&a.G.Dj},N8=function(a,
b,c,d){a.loaded&&a.unload();
null!=c&&(a.O=c);a.A=b;a.load(d)},J8=function(a,b,c){var d=O8.fb;
a.C={};g.Aa(a.C,O8);a.C.fb={};g.Aa(a.C.fb,d);a.D={fb:{}};var e=b.backgroundOverride?a.D:a.C,f=b.background||d.background;c8.test(f);e.fb.background=f;e=b.colorOverride?a.D:a.C;f=b.color||d.color;c8.test(f);e.fb.color=f;e=b.windowColorOverride?a.D:a.C;f=b.windowColor||O8.windowColor;c8.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.D:a.C;f=b.backgroundOpacity;null==f&&(f=d.Ce);e.fb.Ce=f;e=b.fontSizeIncrementOverride?a.D:a.C;f=b.fontSizeIncrement;null==f&&(f=d.hi);e.fb.hi=f;e=b.textOpacityOverride?
a.D:a.C;f=b.textOpacity;null==f&&(f=d.Xg);e.fb.Xg=f;e=b.windowOpacityOverride?a.D:a.C;f=b.windowOpacity;null==f&&(f=O8.ij);e.ij=f;e=b.charEdgeStyleOverride?a.D:a.C;f=b.charEdgeStyle;null==f&&(f=d.Tf);e.fb.Tf=f;e=b.fontFamilyOverride?a.D:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.fb.fontFamily=f;a.loaded&&a.Ar();c&&P8(a,"display-settings",b)},Vta=function(a,b){if(b&&!a.F){var c=e8({dj:0,
lang:"en"});a.F=[c,new Z7(c.start,c.end-c.start,0,c.id,g.L("YTP_SAMPLE_SUBTITLES"))];g.UD(a.g,a.F)}else!b&&a.F&&(Uta(a,a.F),a.F=null)},Uta=function(a,b){g.Uz(a.g,b);
(0,g.K)(b,function(a){g.Ie(this.J,a)},a);
a.aa.pe()},Wta=function(a,b){return a&&g.y(a)&&c8.test(a)?a:b},Xta=function(a,b){return g.ua(a)&&!(0,window.isNaN)(a)?Math.max(0,Math.min(1,(0,window.parseFloat)(a))):b},Zta=function(a,b){if(a&&g.y(a)){var c=Yta.indexOf(a);
return-1!=c?c:b}return b},aua=function(a,b){if(a&&g.y(a)){var c=$ta.indexOf(a);
return-1!=c?c:b}return b},bua=function(a,b){return g.ua(a)&&!(0,window.isNaN)(a)?g.Sh(a,-2,4):b},K8=function(a,b){if(!a.W)return null;
var c;try{c=a.W.get(b)}catch(d){a.W.remove(b)}return c},P8=function(a,b,c){if(a.W)try{a.W.set(b,c)}catch(d){}};
g.vG.prototype.pn=N7(6,function(){return!!this.g.textTracks});
g.xG.prototype.pn=N7(5,function(){return!1});
g.vG.prototype.kl=N7(4,function(a){for(var b=0;b<a.length;b++)this.g.appendChild(a[b])});
g.xG.prototype.kl=N7(3,function(){});
g.ek.prototype.J=N7(2,function(a){return a?this.toString()==a.toString():!1});
g.Fj.prototype.Zl=N7(1,function(a){return(a=g.Gj(this,a))?a.o:0});
g.Ij.prototype.Zl=N7(0,function(){return 0});
var kta=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],jta=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632];Q7.prototype.Hl=function(a){this.Te=a.Te;this.timestamp=a.timestamp;this.g=a.g};
Q7.prototype.reset=function(){this.timestamp=this.Te=0;this.g=!1};
R7.prototype.set=function(a){this.g=a};
R7.prototype.get=function(){return this.g};
var ota=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255],d8=0;
S7.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.A[b][c].reset();this.B=a;this.g=0;this.o=this.Bc=1};
g.B(Y7,g.ds);g.B(Z7,g.ds);var Gta=/^#(?:[0-9a-f]{3}){1,2}$/i;$7.prototype.reset=function(a,b){this.C=b;this.style.set(2);this.o=this.D;this.A=this.F;this.g=this.o;var c=(a<<2)+(b<<1)+0;this.D.reset(c);this.F.reset(c);this.G.reset((a<<2)+(b<<1)+1)};
b8.prototype.clear=function(){this.g=0};
b8.prototype.update=function(){this.g=2==this.g?1:0};
b8.prototype.matches=function(a,b){return 0!=this.g&&a==this.A&&b==this.o};
var c8=/^#(?:[0-9a-f]{3}){1,2}$/i,Hta=/#(.)(.)(.)/;f8.prototype.reset=function(a){this.C=a;this.g.clear();this.B=this.A;this.A.reset(a,0);this.D.reset(a,1)};
sta.prototype.B=function(){};
var cua=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/,dua=/(?:\r\n|\r|\n){2,}/,eua=/^NOTE/,fua=0;g.ca(h8,sta);h8.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+d8++;c=c/1E3-this.F;d=d/1E3-this.F;a=new Y7(c,d-c,5,f,{textAlign:0,vg:0,Ch:2.5*b,Jh:5.33*a});e=new Z7(c,d-c,5,f,e);this.o.push(a);this.o.push(e)}};
i8.prototype.clear=function(){this.B=this.o=this.mode=0;this.g=[];this.reset()};
i8.prototype.reset=function(){this.mode=0;this.C.reset(0);this.D.reset(1)};
var Lta=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;g.B(k8,j8);
k8.prototype.g=function(a){var b=[];this.o||(this.o=e8(),this.A[this.o.id]=this.o,b.push(this.o));for(a=a.firstChild.firstChild;a;){switch(a.tagName){case "window":var c=a,d=b,e=c.getAttribute("id");a:{var f=c,k=this.A[e];if(f.getAttribute("t")||f.getAttribute("start")){c=f.getAttribute("start")?1E3*(0,window.parseFloat)(f.getAttribute("start")):(0,window.parseInt)(f.getAttribute("t"),10);k&&(k.end>=c?k.end=c:k=null);switch(f.getAttribute("op")){case "kill":c=null;break a;case "define":k=null}k||
(k=e8());var l={};k&&(g.Aa(l,k.params),k=k.params.fb)&&(l.fb={},g.Aa(l.fb,k));f.getAttribute("rc")&&(l.fn=(0,window.parseInt)(f.getAttribute("rc"),10));f.getAttribute("cc")&&(l.ou=(0,window.parseInt)(f.getAttribute("cc"),10));f.getAttribute("ap")&&(k=(0,window.parseInt)(f.getAttribute("ap"),10),l.vg=0>k||8<k?7:k);f.getAttribute("ah")&&(l.Ch=(0,window.parseInt)(f.getAttribute("ah"),10));f.getAttribute("av")&&(l.Jh=(0,window.parseInt)(f.getAttribute("av"),10));f.getAttribute("vs")&&(l.isVisible=!!f.getAttribute("vs"));
f.getAttribute("ju")&&(l.textAlign=(0,window.parseInt)(f.getAttribute("ju"),10));f.getAttribute("pd")&&(l.dj=1,0==(0,window.parseInt)(f.getAttribute("pd"),10)&&(l.dj=0));f.getAttribute("bc")&&(l.fb||(l.fb={}),l.fb.backgroundColor=f.getAttribute("bc"));f.getAttribute("bo")&&(l.fb||(l.fb={}),l.fb.Ce=(0,window.parseInt)(f.getAttribute("bo"),10)/100);f.getAttribute("fc")&&(l.fb||(l.fb={}),l.fb.color=f.getAttribute("fc"));f.getAttribute("sd")&&(l.XN=(0,window.parseInt)(f.getAttribute("sd"),10));k=(0,window.parseInt)(f.getAttribute("d"),
10)||1E3*(0,window.parseFloat)(f.getAttribute("dur"))||0x8000000000000;f=f.getAttribute("id")||"0";c=new Y7(c,k,0,f,l)}else c=null}this.A[e]=c;d.push(c);break;case "text":for(d=b,e=[],vta(a,this.o.id,e),c=0;c<e.length;c++)l=e[c],this.A[l.windowId]&&d.push(l)}a=a.nextSibling}return b};
g.B(l8,j8);
l8.prototype.g=function(a,b){for(var c=[],d=a.split(dua),e=1;e<d.length;e++){var f=d[e],k=b,l=c;if(""!=f&&!eua.test(f)){var m=g.k4.exec(f);if(m&&3<=m.length){var n=m8(m[1]),m=m8(m[2])-n,f=f.substring(g.k4.lastIndex);g.k4.lastIndex=0;var k=n+k,n=m,q=f,m={};this.o||(this.o=e8({zq:0}),l.push(this.o));var t=this.o,f=5;if(0>q.indexOf("<"))l.push(new Z7(k,n,f,t.id,q,!1,g.Cb(m)?void 0:m));else{q=q.split(cua);1!=q.length&&(f=6,t="_"+fua++,t=new Y7(k,n,f,t,{}),l.push(t));for(var v=k,w=0;w<q.length;w++){var A=q[w];
if(0==w%2){var F=g.zt("<html>"+A+"</html>"),R;F.getElementsByTagName("parsererror").length?(R=F.createElement("span"),R.appendChild(F.createTextNode(A))):R=F.firstChild;zta(this,v,n-(v-k),f,t,0<w,R,m,l)}else v=m8(A)}}}g.k4.lastIndex=0}}return c};
g.ca(n8,j8);n8.prototype.g=function(a){a=new h8(a,0,this.A);if(uta(a)){for(;a.g<a.A.byteLength;)for(0==a.version&&(a.D=tta(a)*(1E3/45)),a.C=g8(a);0<a.C;a.C--){var b=g8(a),c=g8(a),d=g8(a);b&4&&0==(b&3)&&(b=this.o,b.g.push({time:a.D,type:0,$t:c,au:d,order:b.g.length}))}xta(this.o,a);return a.o}return[]};
g.B(o8,j8);
o8.prototype.g=function(a){a.firstChild.getAttribute("format");var b,c;a=a.firstChild.childNodes;for(var d=0;d<a.length;d++){var e=a[d];switch(e.tagName){case "head":b=e;break;case "body":c=e}}if(b)for(b=b.childNodes,a=0;a<b.length;a++){var f=b[a];switch(f.tagName){case "pen":var e=f.getAttribute("id"),d=this.o,k=f,f={},l=k.getAttribute("p");l&&g.Aa(f,this.o[l]);l=q8(k,"b");null!=l&&(f.bold=l);l=q8(k,"i");null!=l&&(f.rq=l);l=q8(k,"u");null!=l&&(f.yr=l);l=r8(k,"et");null!=l&&(f.Tf=l);l=r8(k,"of");
null!=l&&(f.offset=l);l=s8(k,"bc");null!=l&&(f.background=l);l=s8(k,"ec");null!=l&&(f.eu=l);l=s8(k,"fc");null!=l&&(f.color=l);l=r8(k,"fs");void 0!=l&&0!=l&&(f.fontFamily=l);l=p8(k,"sz");void 0!=l&&(f.hi=l/100-1);l=p8(k,"bo");void 0!=l&&(f.Ce=l/255);k=p8(k,"fo");void 0!=k&&(f.Xg=k/255);d[e]=f;break;case "ws":d=f.getAttribute("id");this.D[d]=Ata(this,f);break;case "wp":d=f.getAttribute("id"),this.C[d]=Bta(this,f)}}b=[];if(c){a={};c=c.childNodes;for(var d=void 0,m,e=0;e<c.length;e++)switch(f=c[e],f.tagName){case "w":var n=
Cta(this,f,!1);(f=a[n.id])&&f.end>n.start&&(f.end=n.start);a[n.id]=n;b.push(n);break;case "p":var q=f,t=d,v=m,k=[],l=q.getAttribute("w")||this.A,w=!!q8(q,"a"),A=p8(q,"t")||0,F=p8(q,"d")||5E3;!v&&!w&&t&&t.windowId==l&&t.end>A&&(t.end=A);for(var t=w?6:5,v=this.o[q.getAttribute("p")],q=q.childNodes,R=0;R<q.length;R++){var I=q[R];0<R&&(w=!0);if("s"==I.tagName)var Ma=I,I=A,tb=F,ga=l,md=w,Rb=t,Jf=Ma.textContent?Ma.textContent:"",qi=this.o[Ma.getAttribute("p")],Ma=p8(Ma,"t")||0,I=new Z7(I+Ma,tb-Ma,Rb,ga,
Jf,md,qi);else I=new Z7(A,F,t,l,I.textContent||"",w,v);k.push(I)}d&&"\n"==d.text&&(d.text="");if(0<k.length)for(d=k[k.length-1],m=null!=f.getAttribute("d"),k[0].windowId==this.A&&(n=Cta(this,f,!0),b.push(n)),f=0;f<k.length;f++)l=k[f],k[f].windowId=n.id,n.o.push(l),b.push(l)}}return b};
g.B(t8,j8);t8.prototype.g=function(a){var b=[];this.o||(this.o=e8(this.A),b.push(this.o));a=a.firstChild.childNodes;for(var c=0,d=a.length;c<d;c++)vta(a[c],this.o.id,b);return b};
x8.prototype.contains=function(a){a=g.Se(this.xa,a);return 0<=a||0>a&&1==(-a-1)%2};
x8.prototype.length=function(){return this.xa.length/2};
var Jta=["left","right","center"],gua={Lp:!0};g.B(y8,g.H);y8.prototype.R=function(){y8.N.R.call(this);this.J.removeEventListener("seekto",this.D,this);this.A&&this.A.abort()};
y8.prototype.D=function(a){this.g=g.xe(this.O.Jj(a).g)};
y8.prototype.H=function(){this.isDisposed();var a;if(a=null!==this.g)a=this.g,a=a.g.Ik(a);if(a&&!this.A&&!(this.g&&30<this.g.startTime-this.J.getCurrentTime())){a=this.g;a=a.g.Sn(a);if(!this.F.contains(a.g[0].o)){var b=g.ny(g.Pz(a)),c={format:"RAW",md:(0,g.z)(this.L,this),withCredentials:!0};this.B&&(c.responseType="arraybuffer");this.A=g.BB(b,c);this.o=a;var b=this.F,c=this.o.g[0].o,d=g.Se(b.xa,c);0<=d||0>d&&1==(-d-1)%2||(d=-d-1,0<d&&1==c-b.xa[d-1]&&d<b.xa.length&&1==b.xa[d]-c?(g.He(b.xa,d),g.He(b.xa,
d-1)):0<d&&1==c-b.xa[d-1]?b.xa[d-1]=c:d<b.xa.length&&1==b.xa[d]-c?b.xa[d]=c:(g.Oe(b.xa,d,0,c),g.Oe(b.xa,d+1,0,c)))}this.g=g.xe(a.g)}this.G.start()};
y8.prototype.L=function(a){this.isDisposed();(this.B?!a.response:!a.responseText)||400<=a.status||null===this.C||(this.B?this.C(a.response,1E3*this.o.g[0].startTime):this.C(a.responseText,1E3*this.o.g[0].startTime));this.A=this.o=null};
g.B(z8,g.V);g.h=z8.prototype;g.h.FQ=function(a,b){var c=g.hu(this.element,this.element.parentElement);this.ba=a-c.x;this.ca=b-c.y;g.N(this.element,"ytp-dragging")};
g.h.EQ=function(a,b){var c=g.ku(this.element),d=a-this.ba-.02*this.Ea,e=b-this.ca-.02*this.Ca,f=(d+c.width/2)/this.P*3,f=Math.floor(g.Sh(f,0,2)),k=(e+c.height/2)/this.ka*3,k=Math.floor(g.Sh(k,0,2)),l=f+3*k,d=(d+f/2*c.width)/this.P,d=100*g.Sh(d,0,1),c=(e+k/2*c.height)/this.ka,c=100*g.Sh(c,0,1);this.A.params.vg=l;this.A.params.Jh=c;this.A.params.Ch=d;this.o.vg=l;this.o.Jh=c;this.o.Ch=d;this.Zi(this.C)};
g.h.DQ=function(){g.yh(this.element,"ytp-dragging")};
g.h.Qb=function(){return this.type};
g.h.Zi=function(a){var b=Math.min(this.$u(),this.P),c=this.Yu();g.Tt(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"96%",height:c?c+"px":"96%",margin:"",transform:""});this.Eo(a);a={transform:"",top:"",left:""};b||(a.width="");c||(a.height="");var d=.96*this.o.Ch+2,e=this.o.vg;switch(e){case 0:case 3:case 6:a.left=d+"%";break;case 1:case 4:case 7:a.left=d+"%";d=this.B.offsetWidth;b||d?(b=b||d+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=
100-d+"%"}b=.96*this.o.Jh+2;switch(e){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.B.offsetHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.Tt(this.element,a)};
g.h.Eo=function(a){for(var b=0;b<a.length&&a[b]==this.C[b];b++);if(this.H||this.C.length>b)b=0,this.H=!1,this.C=[],this.F=[],this.G=[],this.D=null,g.Rq(this.B);for(;b<a.length;b++)Kta(this,a[b])};
g.h.$u=function(){return 0};
g.h.Yu=function(){return 0};
g.h.toString=function(){return z8.N.toString.call(this)};
g.B(B8,g.H);B8.prototype.Xu=function(a){var b=this.g.o,c=u8(this.g,!0);a&&0>b&&0<c.length&&(b=0);return 0>b?null:c[b]};
B8.prototype.Zu=function(){return null};
B8.prototype.od=function(){this.o=null};
B8.prototype.R=function(){B8.N.R.call(this);this.od()};
var Sta=/^[^_-]+/;g.B(C8,B8);g.h=C8.prototype;g.h.uq=function(a,b){this.od();var c=this.B.g[a.o];if(c){var d=1E3*c.index.Zl(c.index.li());this.A=new y8(0,this.Y,c,function(c,f){b(c,a,f,d)},g.X(this.Y).sg)}};
g.h.wq=function(a){v8(this.g,new g.ek({format:1,languageCode:g.X(this.Y).sg?"rawcc":"en",languageName:"English",name:"",is_servable:!0,is_default:!0,is_translateable:!1}));a()};
g.h.od=function(){C8.N.od.call(this);this.A&&(this.A.dispose(),this.A=null)};
g.h.Kj=function(){return""};
g.h.R=function(){this.od();C8.N.R.call(this)};
g.B(D8,z8);D8.prototype.ua=function(){g.yh(this.element,"ytp-rollup-mode");this.Zi(this.ha,!0)};
D8.prototype.$u=function(){var a=this.A.params.ou;if(!this.W&&a){var b=g.qd("SPAN");g.br(b,"\u00a0"+(0,g.Zb)("\u2014",a)+"\u00a0");g.Tt(b,A8(this,this.o.fb));this.B.appendChild(b);this.W=b.offsetWidth;this.B.removeChild(b)}return this.W};
D8.prototype.Yu=function(){return this.A.params.fn*E8(this)};
D8.prototype.Zi=function(a,b){this.ha=a;if(E8(this)){for(var c=0,d=0;c<this.C.length&&d<a.length;c++)this.C[c]==a[d]&&d++;0<d&&d<a.length&&(a=this.C.concat(a.slice(d)));c=1;for(d=0;d<a.length;d++){var e=a[d];g.y(e.text)&&(c+=e.text.split("\n").length-1,e.C||0==d||c++)}c=this.A.params.fn-c;c!=this.M&&(b||(0,window.isNaN)(this.M)||(g.N(this.element,"ytp-rollup-mode"),this.da.pe()),d="",c&&(d="translateY("+Math.ceil(c*E8(this))+"px)"),g.Tt(this.B,"transform",d),this.M=c);D8.N.Zi.call(this,a)}else D8.N.Zi.call(this,
a)};
g.B(F8,z8);F8.prototype.Eo=function(a){var b=this.A.o;F8.N.Eo.call(this,a);var c,d;for(a=a.length;a<b.length;a++){var e=b[a],f;d&&e.o==c?f=d:(f={},g.Aa(f,e.o),g.Aa(f,gua),c=e.o,d=f);Kta(this,e,f)}};
g.B(G8,B8);g.h=G8.prototype;g.h.uq=function(a,b){this.isDisposed();var c=this.Kj(a),d=(0,g.z)(function(c){this.A=null;b(c.responseText,a)},this);
this.od();this.A=g.BB(c,{format:"RAW",Gb:d,withCredentials:!0});Fta(this.g,a)};
g.h.wq=function(a,b,c){var d=this.B;b={type:"list",tlangs:1,v:this.C,fmts:Number(b||!1),vssids:1};this.ew&&(b.asrs=1);d=g.Jk(d,b);b=(0,g.z)(function(b){this.A=null;if((b=b.responseXML)&&b.firstChild){for(var d=this.g,e=b.getElementsByTagName("track"),l=e.length,m=0;m<l;m++){var n=e[m].getAttribute("formats"),q=c,t=e[m].getAttribute("lang_code"),v=e[m].getAttribute("lang_translated"),w=e[m].getAttribute("name"),A=e[m].getAttribute("kind"),F=e[m].getAttribute("id"),R="true"==e[m].getAttribute("lang_default"),
I="true"==e[m].getAttribute("cantran"),Ma=e[m].getAttribute("vss_id");v8(d,new g.ek({formats:n,format:q,languageCode:t,languageName:v,name:w,kind:A,id:F,is_servable:!0,is_default:R,is_translateable:I,vss_id:Ma}))}b=b.getElementsByTagName("target");d=b.length;for(e=0;e<d;e++)l=b[e].getAttribute("lang_code"),m=b[e].getAttribute("lang_translated"),n=b[e].getAttribute("lang_original"),q=b[e].getAttribute("id"),t="true"==b[e].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,
id:q,is_default:t},this.F[l.languageCode]=l.languageName,this.D.push(new g.$c(l))}a()},this);
this.od();this.A=g.BB(d,{format:"RAW",Gb:b,withCredentials:!0})};
g.h.Kj=function(a){var b=this.B,c={v:this.C,type:"track",lang:a.o,name:a.C,kind:a.B,fmt:a.A};a.g&&(c.tlang=O7(a));return b=g.Jk(b,c)};
g.h.od=function(){G8.N.od.call(this);this.A&&this.A.abort()};
g.h.R=function(){this.od();G8.N.R.call(this)};
g.B(H8,B8);g.h=H8.prototype;g.h.uq=function(a,b,c){this.isDisposed();var d=this.Kj(a),e=(0,g.z)(function(c){this.B=null;b(c.responseText,a)},this);
this.od();this.B=g.BB(d,{format:"RAW",Gb:e,withCredentials:!0});c&&this.A&&this.A.Dj!=a&&(this.A.ci=a)};
g.h.wq=function(a,b,c,d){this.C=c;if(this.A=d||null)for(b=0;b<this.A.captionTracks.length;b++)v8(this.g,this.A.captionTracks[b]);a()};
g.h.Kj=function(a){var b=a.H,c={};if(this.C||a.A)c.fmt=this.C||"srv"+a.A;a.g&&(c.tlang=a.g.languageCode);return g.Jk(b,c)};
g.h.Zu=function(){return this.A?this.A.Dj:null};
g.h.Xu=function(){return this.A?this.A.ci:null};
g.h.od=function(){H8.N.od.call(this);this.B&&this.B.abort()};
g.h.R=function(){this.od();H8.N.R.call(this)};
var O8={windowColor:"#080808",ij:0,textAlign:2,vg:7,Ch:50,Jh:100,fb:{background:"#080808",Ce:.75,Tf:0,color:"#fff",fontFamily:4,hi:0,Xg:1,offset:1}},Yta=["none","raised","depressed","uniform","dropShadow"],$ta="default monoSerif propSerif monoSans propSans casual cursive smallCaps".split(" ");g.B(L8,g.gv);g.h=L8.prototype;g.h.R=function(){I8(this)||Vta(this,!1);L8.N.R.call(this)};
g.h.load=function(a){L8.N.load.call(this);this.G=this.g.Nh();if(this.o||a)this.A?(a?this.Zx(a,this.A):3!=this.g.Va()&&this.o.uq(this.A,(0,g.z)(this.Zx,this),g.X(this.g).experiments.g("legacy_default_captions")),this.g.va("captionschanged",P7(this.A))):this.g.va("onCaptionsTrackListChanged");else{var b;this.B.za?b=new C8(this.B.ra,this.g):this.B.captionTracks.length?b=new H8(this.B):b=new G8(this.B.xl,this.B.videoId,this.B.ai||this.X.ai||this.B.hf("yt:cc_default_lang")||this.X.na,this.B.vl);this.o=
b;b.wq((0,g.z)(this.lM,this),!0,I8(this)?"vtt":void 0,this.g.Nh())}};
g.h.unload=function(){if(I8(this))for(var a=g.Dq("track",void 0,this.da.o),b=0;b<a.length;b++)g.Uq(a[b]);else g.vz(this.fa),g.aT(this.g,"captions"),this.J=[],this.o&&this.o.od(),this.F&&g.UD(this.g,this.F),this.Ar();L8.N.unload.call(this);(a=g.OS(this.g.app))&&g.lW(a);this.g.va("captionschanged",{})};
g.h.lM=function(){var a;if(this.O||Rta(this))a=Tta(this,this.O);if(I8(this))for(var b=u8(this.o.g,!0),c=0;c<b.length;c++){var d=b[c],e={kind:"subtitles",label:g.fk(d),srclang:O7(d),src:this.o.Kj(d)};d==a&&(e["default"]=1);this.Y.app.F.kl([g.S("TRACK",e)])}else!this.A&&a&&N8(this,a),this.g.va("onCaptionsTrackListChanged"),this.g.va("onApiChange")};
g.h.gO=function(){this.loaded&&!I8(this)&&this.unload()};
g.h.Zx=function(a,b,c,d){if(a){a=Nta(this.o,a,b,c,d);c={trackName:b.C,trackKind:b.B,trackLangCode:O7(b)};b.g&&(c.fromLangCode=b.o);g.VS(this.g,"cc",c);if(this.A!=M8(this)){if(this.O&&!g.QN(this.X)&&!g.YP(this.X)){g.vz(this.fa);b=e8({vg:0,Ch:5,Jh:5,fn:2,textAlign:0,dj:0,lang:"en"});this.L=[b];c=g.L("YTP_CLICK_FOR_SETTINGS").split("$GEAR_ICON");this.ca||(d=new g.Av(g.Ki()),g.J(this,d),this.ca=d.element);d=b.end-b.start;var e=g.fk(this.A);e&&this.L.push(new Z7(b.start,d,0,b.id,e));this.L.push(new Z7(b.start,
d,0,b.id,c[0]),new Z7(b.start,d,0,b.id,this.ca,!0),new Z7(b.start,d,0,b.id,c[1],!0));g.UD(this.g,this.L);this.fa.pe()}if(this.O||g.QN(this.X))P8(this,"module-enabled",!0),g.X(this.g).experiments.g("legacy_default_captions")||(b=O7(this.A),c=K8(this,"recent-langs"),g.ra(c)||(c=[]),g.Ie(c,b),c.unshift(b),3<c.length&&(c.length=3),this.G&&(this.G.ci=this.A));(b=g.OS(this.g.app))&&g.lW(b)}g.UD(this.g,a);this.O=!1}};
g.h.nQ=function(a){this.J.push(a);this.aa.pe()};
g.h.oQ=function(a){g.Ie(this.J,a);this.aa.pe()};
g.h.gN=function(a){if(a instanceof Y7){var b=this.H[a.id];b&&b.A!=a&&(b.dispose(),delete this.H[a.id],b=null);if(!b){var b=this.H,c=a.id;a:{var d=this.da.Sa(),e=g.AI(this.da,!0).height;switch(null!=a.params.zq?a.params.zq:a.params.XN?2:1<a.o.length?1:0){case 1:a=new F8(a,this.C,this.D,e,d.width,d.height);break a;case 2:a=new D8(a,this.C,this.D,e,d.width,d.height);break a;default:a=new z8(a,this.C,this.D,e,d.width,d.height)}}b[c]=a}}else b=a.windowId,this.M[b]||(this.M[b]=[]),this.M[b].push(a)};
g.h.tN=function(){Uta(this,this.L);this.L=null};
g.h.wz=function(){this.aa.stop();Pta(this.M);this.J.sort(g.es);(0,g.K)(this.J,this.gN,this);g.pb(this.H,function(a,b){!this.M[b]||this.F&&-1==this.F.indexOf(a.A)?(a.dispose(),delete this.H[b]):(a.element.parentNode||g.cT(this.g,a.element,5),a.Zi(this.M[b]))},this)};
g.h.Fy=function(){J8(this,{},!0)};
g.h.vp=function(){var a=O8.fb,a={background:a.background,backgroundOpacity:a.Ce,charEdgeStyle:a.Tf,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.hi,textOpacity:a.Xg,windowColor:O8.windowColor,windowOpacity:O8.ij},b=K8(this,"display-settings"),c;for(c in b)null!=b[c]&&(a[c]=b[c]);return a};
g.h.Dr=function(a,b){var c={};g.Aa(c,K8(this,"display-settings"));g.Aa(c,a);J8(this,c,b);this.g.U("captionssettingschanged")};
g.h.Ar=function(){!I8(this)&&this.loaded&&(g.pb(this.H,function(a,b){a.dispose();delete this.H[b]},this),this.wz())};
g.h.AA=function(a,b){switch(a){case "fontSize":if((0,window.isNaN)(b))break;var c=g.Sh(b,-2,4);this.Dr({fontSizeIncrement:c});return c;case "reload":b&&!I8(this)&&N8(this,this.A,!0);break;case "stickyLoading":void 0!=b&&this.X.Db&&P8(this,"module-enabled",!!b);break;case "track":if(!this.o)return{};if(b){if(I8(this))break;if(!g.wa(b))break;if(g.Cb(b)){N8(this,null,!0);break}for(var d,e=u8(this.o.g,!0),c=0;c<e.length;c++){var f=e[c];f.o!=b.languageCode||d&&f.D!=b.languageName||(d=b.translationLanguage?
ita(f,b.translationLanguage):f)}!d||d==this.A&&this.loaded||N8(this,d,!0)}else return this.loaded&&this.A&&this.A!=M8(this)?P7(this.A):{};return"";case "tracklist":return this.o?(0,g.M)(u8(this.o.g,b&&b.includeAsr),function(a){return P7(a)}):[];
case "translationLanguages":return this.o?this.o.D:[];case "displaySettings":d=this.vp();if(g.QN(this.X)&&b&&g.wa(b))if(b.reset)this.Fy();else{f={};for(c in b)switch(c){case "color":case "background":case "windowColor":f[c]=Wta(b[c],d[c]);break;case "textOpacity":case "backgroundOpacity":case "windowOpacity":f[c]=Xta(b[c],d[c]);break;case "charEdgeStyle":f[c]=Zta(b[c],d[c]);break;case "fontSizeIncrement":f[c]=bua(b[c],d[c]);break;case "fontFamilyOption":f.fontFamily=aua(b[c],d[c])}for(e in f)f[e+
"Override"]=!0;this.Dr(f,!0);d=this.vp()}d.fontFamilyOption=$ta[d.fontFamily];d.charEdgeStyle=Yta[d.charEdgeStyle];return d;case "sampleSubtitles":I8(this)||void 0==b||Vta(this,!!b);break;case "xmlTrack":b&&this.X.Db&&!I8(this)&&N8(this,new g.ek({languageName:b.name}),!1,b.xml)}};
g.h.lQ=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.X.Db&&a.push("stickyLoading","xmlTrack");return a};
g.h.mQ=function(){var a=this.A;return a?{cc:a.F}:{}};
g.h.uz=function(){this.loaded&&this.A?(P8(this,"module-enabled",!1),this.unload()):N8(this,this.A||Tta(this,!0),!0)};
g.h.hJ=function(){this.B.captionTracks.length&&(this.loaded&&this.unload(),Qta(this)&&this.load())};
window._exportCheck==g.Ca&&g.oa("ytmod.player.captions",L8,void 0);})(_yt_player);
